<a href="https://colab.research.google.com/github/preet7890/Codealpha_hangmangam/blob/main/Internship_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Project**
---
## **QueryMart - Retail Sales Database**

In [ ]:
# Step 1: Import Required Libraries
import sqlite3
import requests
import pandas as pd

In [ ]:
import requests
url = "https://github.com/YBIFoundation/SQL/raw/main/QueryMart.db"
response = requests.get(url)
with open("QueryMart.db", "wb") as f:
    f.write(response.content)
conn = sqlite3.connect("QueryMart.db")
print("Database downloaded successfully")

Database downloaded successfully

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# Create helper function
def sql(query):
    return pd.read_sql(query, conn)

In [ ]:
sql(" SELECT name FROM sqlite_master WHERE type='table';")

          name
0    customers
1     products
2   warehouses
3       orders
4  order_items

In [ ]:
# Customer Table
sql("SELECT * FROM customers;")

    customer_id  customer_name       city  age  gender customer_segment
0      CUST0001   Arjun Sharma  Hyderabad   33    Male          Regular
1      CUST0002  Arjun Agarwal  Ahmedabad   23  Female          Regular
2      CUST0003    Aarav Verma    Chennai   32    Male              VIP
3      CUST0004    Amit Chopra  Ahmedabad   44    Male          Premium
4      CUST0005    Nisha Patel      Delhi   28  Female          Premium
..          ...            ...        ...  ...     ...              ...
995    CUST0996    Amit Sharma    Kolkata   40    Male          Premium
996    CUST0997   Vivaan Mehta     Jaipur   53  Female              VIP
997    CUST0998   Simran Singh    Lucknow   29  Female          Premium
998    CUST0999     Riya Patel    Lucknow   53    Male          Regular
999    CUST1000    Kavya Gupta     Jaipur   36  Female              VIP

[1000 rows x 6 columns]

In [ ]:
# Product Table
sql("SELECT * FROM products")

   product_id       product_name     category  unit_price
0     PROD001             Laptop  Electronics    18789.55
1     PROD002         Smartphone  Electronics    47540.64
2     PROD003             Tablet  Electronics    36626.50
3     PROD004        Smart Watch  Electronics    29973.06
4     PROD005  Bluetooth Speaker  Electronics     7885.33
5     PROD006         Headphones  Electronics     7884.13
6     PROD007           Keyboard  Electronics     2998.37
7     PROD008              Mouse  Electronics    43322.19
8     PROD009            Monitor  Electronics    30095.64
9     PROD010         Power Bank  Electronics    35432.82
10    PROD011      Mixer Grinder         Home     1127.17
11    PROD012    Electric Kettle         Home    48498.50
12    PROD013     Vacuum Cleaner         Home    41638.89
13    PROD014       Air Purifier         Home    10695.72
14    PROD015               Iron         Home     9173.07
15    PROD016       Coffee Maker         Home     9251.89
16    PROD017            Toaster         Home    15281.69
17    PROD018                Fan         Home    26285.35
18    PROD019        Room Heater         Home    21654.06
19    PROD020     Water Purifier         Home    14632.33
20    PROD021            T-Shirt      Fashion    30631.46
21    PROD022              Jeans      Fashion     7060.74
22    PROD023             Jacket      Fashion    14678.02
23    PROD024           Sneakers      Fashion    18381.46
24    PROD025       Formal Shirt      Fashion    22857.89
25    PROD026              Dress      Fashion    39280.28
26    PROD027              Saree      Fashion    10063.72
27    PROD028              Kurta      Fashion    25760.30
28    PROD029        Track Pants      Fashion    29661.49
29    PROD030            Handbag      Fashion     2417.88
30    PROD031          Face Wash       Beauty    30416.49
31    PROD032            Shampoo       Beauty     8609.15
32    PROD033        Conditioner       Beauty     3346.07
33    PROD034         Face Cream       Beauty    47449.39
34    PROD035           Lipstick       Beauty    48285.04
35    PROD036            Perfume       Beauty    40439.03
36    PROD037        Body Lotion       Beauty    15300.23
37    PROD038          Sunscreen       Beauty     4973.84
38    PROD039           Hair Oil       Beauty    34243.23
39    PROD040         Makeup Kit       Beauty    22063.61
40    PROD041               Rice      Grocery     6189.71
41    PROD042        Wheat Flour      Grocery    24809.33
42    PROD043        Cooking Oil      Grocery     1815.99
43    PROD044              Sugar      Grocery    45475.09
44    PROD045                Tea      Grocery    13013.12
45    PROD046             Coffee      Grocery    33159.86
46    PROD047           Biscuits      Grocery    15654.38
47    PROD048              Pasta      Grocery    26051.39
48    PROD049   Breakfast Cereal      Grocery    27380.84
49    PROD050             Spices      Grocery     9324.24

In [ ]:
# Orders Table
sql("SELECT * FROM order_items")

,item_id,order_id,product_id,quantity,unit_price,discount_percent,gross_amount,discount_amount,net_amount,shipping_cost
0,ITEM000001,ORD00001,PROD022,4,7060.74,20,28242.96,5648.59,22594.37,83.72
1,ITEM000002,ORD00002,PROD003,1,36626.50,0,36626.50,0.00,36626.50,62.54
2,ITEM000003,ORD00002,PROD048,2,26051.39,15,52102.78,7815.42,44287.36,34.19
3,ITEM000004,ORD00002,PROD045,5,13013.12,0,65065.60,0.00,65065.60,93.24
4,ITEM000005,ORD00003,PROD036,2,40439.03,10,80878.06,8087.81,72790.25,427.01
...,...,...,...,...,...,...,...,...,...,...
15126,ITEM015127,ORD05000,PROD032,4,8609.15,5,34436.60,1721.83,32714.77,449.17
15127,ITEM015128,ORD05000,PROD008,5,43322.19,10,216610.95,21661.10,194949.86,291.64
15128,ITEM015129,ORD05000,PROD048,4,26051.39,5,104205.56,5210.28,98995.28,367.06
15129,ITEM015130,ORD05000,PROD024,3,18381.46,0,55144.38,0.00,55144.38,407.49
15130,ITEM015131,ORD05000,PROD029,5,29661.49,15,148307.45,22246.12,126061.33,96.37

In [ ]:
# Calculate Total Revenue
sql("SELECT SUM(net_amount) FROM order_items")

   SUM(net_amount)
0     8.979608e+08

In [ ]:
sql("SELECT * FROM orders")

,order_id,customer_id,warehouse_id,order_date,payment_method,order_status
0,ORD00001,CUST0465,WH001,2025-07-07,Net Banking,Delivered
1,ORD00002,CUST0905,WH001,2025-04-05,Net Banking,Shipped
2,ORD00003,CUST0245,WH006,2025-11-14,UPI,Delivered
3,ORD00004,CUST0839,WH007,2025-10-03,Credit Card,Delivered
4,ORD00005,CUST0785,WH009,2025-09-12,Credit Card,Delivered
...,...,...,...,...,...,...
4995,ORD04996,CUST0389,WH006,2025-12-12,Credit Card,Shipped
4996,ORD04997,CUST0206,WH003,2025-11-16,Credit Card,Shipped
4997,ORD04998,CUST0078,WH005,2025-10-24,Credit Card,Returned
4998,ORD04999,CUST0014,WH008,2025-12-27,UPI,Delivered
4999,ORD05000,CUST0490,WH004,2025-05-26,Cash,Delivered

In [ ]:
# Find unique payment methods
sql("SELECT DISTINCT payment_method	FROM orders")

  payment_method
0    Net Banking
1            UPI
2    Credit Card
3           Cash
4     Debit Card

In [ ]:
# Find unique order statuses
sql("SELECT DISTINCT order_status FROM orders")

  order_status
0    Delivered
1      Shipped
2    Cancelled
3     Returned

In [ ]:
#Find all delivered orders
sql("SELECT * FROM orders WHERE order_status = 'Delivered'")

,order_id,customer_id,warehouse_id,order_date,payment_method,order_status
0,ORD00001,CUST0465,WH001,2025-07-07,Net Banking,Delivered
1,ORD00003,CUST0245,WH006,2025-11-14,UPI,Delivered
2,ORD00004,CUST0839,WH007,2025-10-03,Credit Card,Delivered
3,ORD00005,CUST0785,WH009,2025-09-12,Credit Card,Delivered
4,ORD00006,CUST0420,WH006,2025-06-15,UPI,Delivered
...,...,...,...,...,...,...
3706,ORD04990,CUST0647,WH008,2025-10-26,UPI,Delivered
3707,ORD04992,CUST0789,WH008,2025-07-26,Cash,Delivered
3708,ORD04994,CUST0295,WH005,2025-04-10,UPI,Delivered
3709,ORD04999,CUST0014,WH008,2025-12-27,UPI,Delivered
3710,ORD05000,CUST0490,WH004,2025-05-26,Cash,Delivered

In [ ]:
# Find all orders placed after June 2025
sql("SELECT * FROM orders WHERE order_date >= '2025-07-01'")

,order_id,customer_id,warehouse_id,order_date,payment_method,order_status
0,ORD00001,CUST0465,WH001,2025-07-07,Net Banking,Delivered
1,ORD00003,CUST0245,WH006,2025-11-14,UPI,Delivered
2,ORD00004,CUST0839,WH007,2025-10-03,Credit Card,Delivered
3,ORD00005,CUST0785,WH009,2025-09-12,Credit Card,Delivered
4,ORD00007,CUST0069,WH001,2025-12-04,Credit Card,Delivered
...,...,...,...,...,...,...
2524,ORD04995,CUST0156,WH003,2025-07-07,Debit Card,Cancelled
2525,ORD04996,CUST0389,WH006,2025-12-12,Credit Card,Shipped
2526,ORD04997,CUST0206,WH003,2025-11-16,Credit Card,Shipped
2527,ORD04998,CUST0078,WH005,2025-10-24,Credit Card,Returned
2528,ORD04999,CUST0014,WH008,2025-12-27,UPI,Delivered

In [ ]:
# Find orders placed between January and March 2025
sql("SELECT * FROM orders WHERE order_date BETWEEN 	'2025-01-01' AND 	'2025-03-31'")

,order_id,customer_id,warehouse_id,order_date,payment_method,order_status
0,ORD00008,CUST0207,WH002,2025-01-17,Cash,Delivered
1,ORD00009,CUST0585,WH007,2025-01-17,Cash,Delivered
2,ORD00016,CUST0968,WH004,2025-02-09,Net Banking,Delivered
3,ORD00022,CUST0547,WH010,2025-03-22,Cash,Cancelled
4,ORD00027,CUST0744,WH001,2025-01-01,Debit Card,Delivered
...,...,...,...,...,...,...
1234,ORD04980,CUST0655,WH008,2025-01-05,Credit Card,Delivered
1235,ORD04981,CUST0973,WH008,2025-03-27,Cash,Delivered
1236,ORD04982,CUST0124,WH009,2025-03-01,Debit Card,Delivered
1237,ORD04983,CUST0710,WH008,2025-03-07,Net Banking,Cancelled
1238,ORD04985,CUST0150,WH002,2025-02-12,UPI,Shipped

In [ ]:
# Find the 10 most expensive products
sql("SELECT * FROM products ORDER BY unit_price DESC LIMIT 10")

  product_id     product_name     category  unit_price
0    PROD012  Electric Kettle         Home    48498.50
1    PROD035         Lipstick       Beauty    48285.04
2    PROD002       Smartphone  Electronics    47540.64
3    PROD034       Face Cream       Beauty    47449.39
4    PROD044            Sugar      Grocery    45475.09
5    PROD008            Mouse  Electronics    43322.19
6    PROD013   Vacuum Cleaner         Home    41638.89
7    PROD036          Perfume       Beauty    40439.03
8    PROD026            Dress      Fashion    39280.28
9    PROD003           Tablet  Electronics    36626.50

In [ ]:
# Calculate average order-item revenue
sql("SELECT AVG(net_amount) FROM order_items")

   AVG(net_amount)
0     59345.768945

In [ ]:
# Find number of products in each category
sql("SELECT category, COUNT(*), AVG(unit_price) FROM products GROUP BY category")

      category  COUNT(*)  AVG(unit_price)
0       Beauty        10        25512.608
1  Electronics        10        26054.823
2      Fashion        10        20079.324
3      Grocery        10        20287.395
4         Home        10        19823.867